Fix missing if-clause when database is disabled
If the database provided is being disabled in values.yaml (e.g. because of using a replicated database solution) the helm installation would fail with: 
Error: INSTALLATION FAILED: template: supabase/templates/db/storage.yaml:1:14: executing "supabase/templates/db/storage.yaml" at <.Values.db.persistence.enabled>: nil pointer evaluating interface {}.enabled